//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train
    {
        public int TrainNo { get; set; }
        public string Name { get; set; }
        public System.DateTime Departure { get; set; }
        public string Region { get; set; }
    }
}
