//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.NetApp.LocalServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalServiceReference.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (MethodOverloading) of message MethodOverloading does not match the default value (HelloWorld1)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MethodOverloading", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServices.NetApp.LocalServiceReference.MethodOverloading1 HelloWorld1(WebServices.NetApp.LocalServiceReference.MethodOverloading request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MethodOverloading", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.MethodOverloading1> HelloWorld1Async(WebServices.NetApp.LocalServiceReference.MethodOverloading request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServices.NetApp.LocalServiceReference.Employee[] GetAllEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.Employee[]> GetAllEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Calculation(int firstNumber, string operation, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Calculation", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CalculationAsync(int firstNumber, string operation, int secondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSessionName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddSessionName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSessionName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddSessionNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessionName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetSessionName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessionName", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> GetSessionNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncrementSessionCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void IncrementSessionCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncrementSessionCount", ReplyAction="*")]
        System.Threading.Tasks.Task IncrementSessionCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessionCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetSessionCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSessionCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetSessionCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimeOutMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TimeOutMethod();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimeOutMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TimeOutMethodAsync();
        
        // CODEGEN: Generating message contract since message AuthMethodRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServices.NetApp.LocalServiceReference.AuthMethodResponse AuthMethod(WebServices.NetApp.LocalServiceReference.AuthMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.AuthMethodResponse> AuthMethodAsync(WebServices.NetApp.LocalServiceReference.AuthMethodRequest request);
        
        // CODEGEN: Generating message contract since message TokenAuthMethodRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenAuthMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServices.NetApp.LocalServiceReference.TokenAuthMethodResponse TokenAuthMethod(WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TokenAuthMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.TokenAuthMethodResponse> TokenAuthMethodAsync(WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest request);
        
        // CODEGEN: Generating message contract since message ValidateTokenRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServices.NetApp.LocalServiceReference.ValidateTokenResponse ValidateToken(WebServices.NetApp.LocalServiceReference.ValidateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.ValidateTokenResponse> ValidateTokenAsync(WebServices.NetApp.LocalServiceReference.ValidateTokenRequest request);
        
        // CODEGEN: Generating message contract since message EncryptDecryptMethodRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDecryptMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodResponse EncryptDecryptMethod(WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDecryptMethod", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodResponse> EncryptDecryptMethodAsync(WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MethodOverloading", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MethodOverloading {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string name;
        
        public MethodOverloading() {
        }
        
        public MethodOverloading(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MethodOverloadingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MethodOverloading1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MethodOverloadingResult;
        
        public MethodOverloading1() {
        }
        
        public MethodOverloading1(string MethodOverloadingResult) {
            this.MethodOverloadingResult = MethodOverloadingResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int employeeIDField;
        
        private string lastNameField;
        
        private string firstNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int EmployeeID {
            get {
                return this.employeeIDField;
            }
            set {
                this.employeeIDField = value;
                this.RaisePropertyChanged("EmployeeID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceAuth : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private bool isCredentialsValidField;
        
        private bool isTokenValidField;
        
        private string tokenField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsCredentialsValid {
            get {
                return this.isCredentialsValidField;
            }
            set {
                this.isCredentialsValidField = value;
                this.RaisePropertyChanged("IsCredentialsValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsTokenValid {
            get {
                return this.isTokenValidField;
            }
            set {
                this.isTokenValidField = value;
                this.RaisePropertyChanged("IsTokenValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthMethodRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth;
        
        public AuthMethodRequest() {
        }
        
        public AuthMethodRequest(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            this.WebServiceAuth = WebServiceAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebServices.NetApp.LocalServiceReference.AuthResponse AuthMethodResult;
        
        public AuthMethodResponse() {
        }
        
        public AuthMethodResponse(WebServices.NetApp.LocalServiceReference.AuthResponse AuthMethodResult) {
            this.AuthMethodResult = AuthMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TokenAuthMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TokenAuthMethodRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth;
        
        public TokenAuthMethodRequest() {
        }
        
        public TokenAuthMethodRequest(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            this.WebServiceAuth = WebServiceAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TokenAuthMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TokenAuthMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebServices.NetApp.LocalServiceReference.AuthResponse TokenAuthMethodResult;
        
        public TokenAuthMethodResponse() {
        }
        
        public TokenAuthMethodResponse(WebServices.NetApp.LocalServiceReference.AuthResponse TokenAuthMethodResult) {
            this.TokenAuthMethodResult = TokenAuthMethodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateTokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth;
        
        public ValidateTokenRequest() {
        }
        
        public ValidateTokenRequest(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            this.WebServiceAuth = WebServiceAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebServices.NetApp.LocalServiceReference.AuthResponse ValidateTokenResult;
        
        public ValidateTokenResponse() {
        }
        
        public ValidateTokenResponse(WebServices.NetApp.LocalServiceReference.AuthResponse ValidateTokenResult) {
            this.ValidateTokenResult = ValidateTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptDecryptMethod", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptDecryptMethodRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth;
        
        public EncryptDecryptMethodRequest() {
        }
        
        public EncryptDecryptMethodRequest(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            this.WebServiceAuth = WebServiceAuth;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EncryptDecryptMethodResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EncryptDecryptMethodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WebServices.NetApp.LocalServiceReference.AuthResponse EncryptDecryptMethodResult;
        
        public EncryptDecryptMethodResponse() {
        }
        
        public EncryptDecryptMethodResponse(WebServices.NetApp.LocalServiceReference.AuthResponse EncryptDecryptMethodResult) {
            this.EncryptDecryptMethodResult = EncryptDecryptMethodResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebServices.NetApp.LocalServiceReference.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebServices.NetApp.LocalServiceReference.WebService1Soap>, WebServices.NetApp.LocalServiceReference.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.NetApp.LocalServiceReference.MethodOverloading1 WebServices.NetApp.LocalServiceReference.WebService1Soap.HelloWorld1(WebServices.NetApp.LocalServiceReference.MethodOverloading request) {
            return base.Channel.HelloWorld1(request);
        }
        
        public string HelloWorld1(string name) {
            WebServices.NetApp.LocalServiceReference.MethodOverloading inValue = new WebServices.NetApp.LocalServiceReference.MethodOverloading();
            inValue.name = name;
            WebServices.NetApp.LocalServiceReference.MethodOverloading1 retVal = ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).HelloWorld1(inValue);
            return retVal.MethodOverloadingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.MethodOverloading1> WebServices.NetApp.LocalServiceReference.WebService1Soap.HelloWorld1Async(WebServices.NetApp.LocalServiceReference.MethodOverloading request) {
            return base.Channel.HelloWorld1Async(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.MethodOverloading1> HelloWorld1Async(string name) {
            WebServices.NetApp.LocalServiceReference.MethodOverloading inValue = new WebServices.NetApp.LocalServiceReference.MethodOverloading();
            inValue.name = name;
            return ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).HelloWorld1Async(inValue);
        }
        
        public WebServices.NetApp.LocalServiceReference.Employee[] GetAllEmployees() {
            return base.Channel.GetAllEmployees();
        }
        
        public System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.Employee[]> GetAllEmployeesAsync() {
            return base.Channel.GetAllEmployeesAsync();
        }
        
        public string Calculation(int firstNumber, string operation, int secondNumber) {
            return base.Channel.Calculation(firstNumber, operation, secondNumber);
        }
        
        public System.Threading.Tasks.Task<string> CalculationAsync(int firstNumber, string operation, int secondNumber) {
            return base.Channel.CalculationAsync(firstNumber, operation, secondNumber);
        }
        
        public string AddSessionName(string name) {
            return base.Channel.AddSessionName(name);
        }
        
        public System.Threading.Tasks.Task<string> AddSessionNameAsync(string name) {
            return base.Channel.AddSessionNameAsync(name);
        }
        
        public string[] GetSessionName() {
            return base.Channel.GetSessionName();
        }
        
        public System.Threading.Tasks.Task<string[]> GetSessionNameAsync() {
            return base.Channel.GetSessionNameAsync();
        }
        
        public void IncrementSessionCount() {
            base.Channel.IncrementSessionCount();
        }
        
        public System.Threading.Tasks.Task IncrementSessionCountAsync() {
            return base.Channel.IncrementSessionCountAsync();
        }
        
        public int GetSessionCount() {
            return base.Channel.GetSessionCount();
        }
        
        public System.Threading.Tasks.Task<int> GetSessionCountAsync() {
            return base.Channel.GetSessionCountAsync();
        }
        
        public string TimeOutMethod() {
            return base.Channel.TimeOutMethod();
        }
        
        public System.Threading.Tasks.Task<string> TimeOutMethodAsync() {
            return base.Channel.TimeOutMethodAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.NetApp.LocalServiceReference.AuthMethodResponse WebServices.NetApp.LocalServiceReference.WebService1Soap.AuthMethod(WebServices.NetApp.LocalServiceReference.AuthMethodRequest request) {
            return base.Channel.AuthMethod(request);
        }
        
        public WebServices.NetApp.LocalServiceReference.AuthResponse AuthMethod(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.AuthMethodRequest inValue = new WebServices.NetApp.LocalServiceReference.AuthMethodRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            WebServices.NetApp.LocalServiceReference.AuthMethodResponse retVal = ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).AuthMethod(inValue);
            return retVal.AuthMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.AuthMethodResponse> WebServices.NetApp.LocalServiceReference.WebService1Soap.AuthMethodAsync(WebServices.NetApp.LocalServiceReference.AuthMethodRequest request) {
            return base.Channel.AuthMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.AuthMethodResponse> AuthMethodAsync(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.AuthMethodRequest inValue = new WebServices.NetApp.LocalServiceReference.AuthMethodRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            return ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).AuthMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.NetApp.LocalServiceReference.TokenAuthMethodResponse WebServices.NetApp.LocalServiceReference.WebService1Soap.TokenAuthMethod(WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest request) {
            return base.Channel.TokenAuthMethod(request);
        }
        
        public WebServices.NetApp.LocalServiceReference.AuthResponse TokenAuthMethod(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest inValue = new WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            WebServices.NetApp.LocalServiceReference.TokenAuthMethodResponse retVal = ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).TokenAuthMethod(inValue);
            return retVal.TokenAuthMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.TokenAuthMethodResponse> WebServices.NetApp.LocalServiceReference.WebService1Soap.TokenAuthMethodAsync(WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest request) {
            return base.Channel.TokenAuthMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.TokenAuthMethodResponse> TokenAuthMethodAsync(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest inValue = new WebServices.NetApp.LocalServiceReference.TokenAuthMethodRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            return ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).TokenAuthMethodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.NetApp.LocalServiceReference.ValidateTokenResponse WebServices.NetApp.LocalServiceReference.WebService1Soap.ValidateToken(WebServices.NetApp.LocalServiceReference.ValidateTokenRequest request) {
            return base.Channel.ValidateToken(request);
        }
        
        public WebServices.NetApp.LocalServiceReference.AuthResponse ValidateToken(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.ValidateTokenRequest inValue = new WebServices.NetApp.LocalServiceReference.ValidateTokenRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            WebServices.NetApp.LocalServiceReference.ValidateTokenResponse retVal = ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).ValidateToken(inValue);
            return retVal.ValidateTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.ValidateTokenResponse> WebServices.NetApp.LocalServiceReference.WebService1Soap.ValidateTokenAsync(WebServices.NetApp.LocalServiceReference.ValidateTokenRequest request) {
            return base.Channel.ValidateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.ValidateTokenResponse> ValidateTokenAsync(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.ValidateTokenRequest inValue = new WebServices.NetApp.LocalServiceReference.ValidateTokenRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            return ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).ValidateTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodResponse WebServices.NetApp.LocalServiceReference.WebService1Soap.EncryptDecryptMethod(WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest request) {
            return base.Channel.EncryptDecryptMethod(request);
        }
        
        public WebServices.NetApp.LocalServiceReference.AuthResponse EncryptDecryptMethod(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest inValue = new WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodResponse retVal = ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).EncryptDecryptMethod(inValue);
            return retVal.EncryptDecryptMethodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodResponse> WebServices.NetApp.LocalServiceReference.WebService1Soap.EncryptDecryptMethodAsync(WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest request) {
            return base.Channel.EncryptDecryptMethodAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodResponse> EncryptDecryptMethodAsync(WebServices.NetApp.LocalServiceReference.WebServiceAuth WebServiceAuth) {
            WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest inValue = new WebServices.NetApp.LocalServiceReference.EncryptDecryptMethodRequest();
            inValue.WebServiceAuth = WebServiceAuth;
            return ((WebServices.NetApp.LocalServiceReference.WebService1Soap)(this)).EncryptDecryptMethodAsync(inValue);
        }
    }
}
